services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-datasupr:/data/db
    networks:
      - datasupr

  app:
    build:
      dockerfile: Dockerfile-dev
    command: npm run dev:docker
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    env_file:
      - ./server/.env
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5173:5173
    networks:
      - datasupr
networks:
  datasupr: {}

volumes:
  mongo-datasupr:
