services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - mongo-datasupr:/data/db
    networks:
      - datasupr

networks:
  datasupr: {}

volumes:
  mongo-datasupr:
