import {
  CHART_COLORS,
  METRIC_COLORS,
} from "../../../../../../constants/colors";

export const METRICS_CONFIG = {
  effectif_sans_cpge: {
    label: "Effectifs d’étudiants inscrits",
    format: "number" as const,
    color: METRIC_COLORS.effectifs,
    category: "Effectifs",
  },
  effectif_sans_cpge_l: {
    label: "1er cycle (Cursus L)",
    format: "number" as const,
    color: METRIC_COLORS.effectifsLicence,
    category: "Effectifs",
  },
  effectif_sans_cpge_m: {
    label: "2ème cycle (Cursus M)",
    format: "number" as const,
    color: METRIC_COLORS.effectifsMaster,
    category: "Effectifs",
  },
  effectif_sans_cpge_d: {
    label: "3ème cycle (Cursus D)",
    format: "number" as const,
    color: METRIC_COLORS.effectifsDoctorat,
    category: "Effectifs",
  },

  taux_encadrement: {
    label: "Taux d'encadrement",
    format: "percent" as const,
    color: METRIC_COLORS.tauxEncadrement,
    category: "Ratios",
    suffix: "%",
  },
  emploi_etpt: {
    label: "Emplois (ETPT)",
    format: "decimal" as const,
    color: METRIC_COLORS.emploiEtpt,
    category: "Personnel",
  },
  charges_de_personnel_produits_encaissables: {
    label: "Charges personnel / Produits",
    format: "percent" as const,
    color: METRIC_COLORS.chargesPersonnel,
    category: "Ratios",
    suffix: "%",
  },

  scsp: {
    label: "SCSP à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.scsp,
    category: "Finances",
  },
  scsp_ipc: {
    label: "SCSP à prix constant",
    format: "euro" as const,
    color: CHART_COLORS.palette[3],
    category: "Finances",
  },
  scsp_par_etudiants: {
    label: "SCSP par étudiant à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[1],
    category: "Finances",
  },
  scsp_par_etudiants_ipc: {
    label: "SCSP par étudiant (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[4],
    category: "Finances",
  },
  scsp_etudiants: {
    label: "Étudiants financés par la SCSP",
    format: "number" as const,
    color: CHART_COLORS.palette[2],
    category: "Finances",
  },
  ressources_propres: {
    label: "Ressources propres à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.ressourcesPropres,
    category: "Finances",
  },
  ressources_propres_ipc: {
    label: "Ressources propres (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[5],
    category: "Finances",
  },
  charges_de_personnel: {
    label: "Charges de personnel à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.chargesPersonnel,
    category: "Finances",
  },
  charges_de_personnel_ipc: {
    label: "Charges de personnel (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[6],
    category: "Finances",
  },
  produits_de_fonctionnement_encaissables: {
    label: "Produits de fonctionnement à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.produitsFonctionnement,
    category: "Finances",
  },
  produits_de_fonctionnement_encaissables_ipc: {
    label: "Produits de fonctionnement (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[7],
    category: "Finances",
  },
  ressources_propres_encaissables: {
    label: "Ressources propres encaissables à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.ressourcesPropres,
    category: "Finances",
  },
  ressources_propres_encaissables_ipc: {
    label: "Ressources propres encaissables (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[8],
    category: "Finances",
  },
  recettes_propres: {
    label: "Recettes propres à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.ressourcesPropres,
    category: "Finances",
  },
  recettes_propres_ipc: {
    label: "Recettes propres (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[9],
    category: "Finances",
  },
  charges_de_fonctionnement_decaissables: {
    label: "Charges de fonctionnement décaissables à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.chargesPersonnel,
    category: "Santé financière",
  },
  charges_de_fonctionnement_decaissables_ipc: {
    label: "Charges de fonctionnement décaissables (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[10],
    category: "Santé financière",
  },
  charges_externes: {
    label: "Charges externes à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.chargesPersonnel,
    category: "Finances",
  },
  charges_externes_ipc: {
    label: "Charges externes (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[11],
    category: "Finances",
  },
  charges_externes_produits_encaissables: {
    label: "Charges externes / Produits encaissables",
    format: "percent" as const,
    color: METRIC_COLORS.chargesPersonnel,
    category: "Ratios",
    suffix: "%",
  },
  excedent_brut_d_exploitation_ebe: {
    label: "Excédent brut d'exploitation (EBE) à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.produitsFonctionnement,
    category: "Finances",
  },
  excedent_brut_d_exploitation_ebe_ipc: {
    label: "Excédent brut d'exploitation (EBE) (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.effectifs,
    category: "Finances",
  },
  acquisitions_d_immobilisations: {
    label: "Acquisitions d'immobilisations à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.effectifsLicence,
    category: "Santé financière",
  },
  acquisitions_d_immobilisations_ipc: {
    label: "Acquisitions d'immobilisations (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.effectifsMaster,
    category: "Santé financière",
  },

  anr_hors_investissements_d_avenir: {
    label: "ANR hors investissements d'avenir",
    format: "euro" as const,
    color: "#A558A0",
    category: "Recherche",
  },
  subventions_union_europeenne: {
    label: "Subventions UE",
    format: "euro" as const,
    color: METRIC_COLORS.subventionsUE,
    category: "Recherche",
  },
  contrats_et_prestations_de_recherche_hors_anr: {
    label: "Contrats recherche",
    format: "euro" as const,
    color: METRIC_COLORS.contratsRecherche,
    category: "Recherche",
  },

  droits_d_inscription: {
    label: "Droits d'inscription",
    format: "euro" as const,
    color: METRIC_COLORS.droitsInscription,
    category: "Formation",
  },
  formation_continue_diplomes_propres_et_vae: {
    label: "Formation continue",
    format: "euro" as const,
    color: METRIC_COLORS.formationContinue,
    category: "Formation",
  },
  taxe_d_apprentissage: {
    label: "Taxe d'apprentissage",
    format: "euro" as const,
    color: CHART_COLORS.palette[5],
    category: "Formation",
  },
  valorisation: {
    label: "Valorisation",
    format: "euro" as const,
    color: CHART_COLORS.palette[6],
    category: "Recherche",
  },
  anr_investissements_d_avenir: {
    label: "ANR investissements d'avenir",
    format: "euro" as const,
    color: CHART_COLORS.palette[7],
    category: "Recherche",
  },
  subventions_de_la_region: {
    label: "Subventions régionales",
    format: "euro" as const,
    color: CHART_COLORS.palette[8],
    category: "Recherche",
  },
  autres_ressources_propres: {
    label: "Autres ressources propres",
    format: "euro" as const,
    color: CHART_COLORS.palette[9],
    category: "Finances",
  },
  autres_subventions: {
    label: "Autres subventions",
    format: "euro" as const,
    color: CHART_COLORS.palette[10],
    category: "Finances",
  },
  tot_ress_formation: {
    label: "Ressources formation à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[11],
    category: "Finances",
  },
  tot_ress_formation_ipc: {
    label: "Ressources formation (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[8],
    category: "Finances",
  },
  tot_ress_recherche: {
    label: "Ressources recherche à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[11],
    category: "Finances",
  },
  tot_ress_recherche_ipc: {
    label: "Ressources recherche (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[9],
    category: "Finances",
  },
  tot_ress_autres_recette: {
    label: "Autres ressources à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[11],
    category: "Finances",
  },
  tot_ress_autres_recette_ipc: {
    label: "Autres ressources (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[10],
    category: "Finances",
  },

  fonds_de_roulement_net_global: {
    label: "Fonds de roulement net global à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[0],
    category: "Santé financière",
  },
  fonds_de_roulement_net_global_ipc: {
    label: "Fonds de roulement net global (à prix constant)",
    format: "euro" as const,
    color: CHART_COLORS.palette[11],
    category: "Santé financière",
  },
  besoin_en_fonds_de_roulement: {
    label: "Besoin en fonds de roulement à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[1],
    category: "Santé financière",
  },
  besoin_en_fonds_de_roulement_ipc: {
    label: "Besoin en fonds de roulement (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.effectifsLicence,
    category: "Santé financière",
  },
  tresorerie: {
    label: "Trésorerie à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[2],
    category: "Santé financière",
  },
  tresorerie_ipc: {
    label: "Trésorerie (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.effectifsMaster,
    category: "Santé financière",
  },
  fonds_de_roulement_en_jours_de_fonctionnement: {
    label: "Fonds de roulement en jours",
    format: "decimal" as const,
    color: CHART_COLORS.palette[3],
    category: "Santé financière",
  },
  tresorerie_en_jours_de_fonctionnement: {
    label: "Trésorerie en jours",
    format: "decimal" as const,
    color: CHART_COLORS.palette[4],
    category: "Santé financière",
  },
  charges_decaissables_produits_encaissables: {
    label: "Charges décaissables / Produits encaissables",
    format: "percent" as const,
    color: CHART_COLORS.palette[5],
    category: "Santé financière",
    suffix: "%",
  },
  taux_de_remuneration_des_permanents: {
    label: "Taux de rémunération des permanents",
    format: "percent" as const,
    color: CHART_COLORS.palette[6],
    category: "Santé financière",
    suffix: "%",
  },
  ressources_propres_produits_encaissables: {
    label: "Ressources propres / Produits encaissables",
    format: "percent" as const,
    color: CHART_COLORS.palette[7],
    category: "Santé financière",
    suffix: "%",
  },
  caf_acquisitions_d_immobilisations: {
    label: "CAF / Acquisitions d'immobilisations",
    format: "percent" as const,
    color: CHART_COLORS.palette[8],
    category: "Santé financière",
    suffix: "%",
  },
  solde_budgetaire: {
    label: "Solde budgétaire à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[9],
    category: "Santé financière",
  },
  solde_budgetaire_ipc: {
    label: "Solde budgétaire (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.effectifsDoctorat,
    category: "Santé financière",
  },
  resultat_net_comptable: {
    label: "Résultat net comptable à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[10],
    category: "Santé financière",
  },
  resultat_net_comptable_ipc: {
    label: "Résultat net comptable (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.tauxEncadrement,
    category: "Santé financière",
  },
  resultat_net_comptable_hors_sie: {
    label: "Résultat net comptable hors SIE à prix courant",
    format: "euro" as const,
    color: CHART_COLORS.palette[11],
    category: "Santé financière",
  },
  resultat_net_comptable_hors_sie_ipc: {
    label: "Résultat net comptable hors SIE (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.emploiEtpt,
    category: "Santé financière",
  },
  capacite_d_autofinancement: {
    label: "Capacité d'autofinancement à prix courant",
    format: "euro" as const,
    color: METRIC_COLORS.effectifs,
    category: "Santé financière",
  },
  capacite_d_autofinancement_ipc: {
    label: "Capacité d'autofinancement (à prix constant)",
    format: "euro" as const,
    color: METRIC_COLORS.scsp,
    category: "Santé financière",
  },
  caf_produits_encaissables: {
    label: "CAF / Produits encaissables",
    format: "percent" as const,
    color: METRIC_COLORS.effectifsLicence,
    category: "Santé financière",
    suffix: "%",
  },

  effectif_sans_cpge_deg0: {
    label: "BAC ou inférieur",
    format: "number" as const,
    color: CHART_COLORS.palette[0],
    category: "Effectifs",
  },
  effectif_sans_cpge_deg1: {
    label: "BAC + 1",
    format: "number" as const,
    color: CHART_COLORS.palette[1],
    category: "Effectifs",
  },
  effectif_sans_cpge_deg2: {
    label: "BAC + 2",
    format: "number" as const,
    color: CHART_COLORS.palette[2],
    category: "Effectifs",
  },
  effectif_sans_cpge_deg3: {
    label: "BAC + 3",
    format: "number" as const,
    color: CHART_COLORS.palette[3],
    category: "Effectifs",
  },
  effectif_sans_cpge_deg4: {
    label: "BAC + 4",
    format: "number" as const,
    color: CHART_COLORS.palette[4],
    category: "Effectifs",
  },
  effectif_sans_cpge_deg5: {
    label: "BAC + 5",
    format: "number" as const,
    color: CHART_COLORS.palette[5],
    category: "Effectifs",
  },
  effectif_sans_cpge_deg6: {
    label: "BAC + 6 et +",
    format: "number" as const,
    color: CHART_COLORS.palette[6],
    category: "Effectifs",
  },
  effectif_sans_cpge_deg9: {
    label: "Indéterminé",
    format: "number" as const,
    color: CHART_COLORS.palette[7],
    category: "Effectifs",
  },

  effectif_sans_cpge_dsa: {
    label: "Droit, Sciences éco., AES",
    format: "number" as const,
    color: CHART_COLORS.palette[0],
    category: "Effectifs",
  },
  effectif_sans_cpge_llsh: {
    label: "Lettres, Langues, SHS",
    format: "number" as const,
    color: CHART_COLORS.palette[1],
    category: "Effectifs",
  },
  effectif_sans_cpge_theo: {
    label: "Théologie",
    format: "number" as const,
    color: CHART_COLORS.palette[2],
    category: "Effectifs",
  },
  effectif_sans_cpge_si: {
    label: "Sciences et Ingénierie",
    format: "number" as const,
    color: CHART_COLORS.palette[3],
    category: "Effectifs",
  },
  effectif_sans_cpge_staps: {
    label: "STAPS",
    format: "number" as const,
    color: CHART_COLORS.palette[4],
    category: "Effectifs",
  },
  effectif_sans_cpge_sante: {
    label: "Santé",
    format: "number" as const,
    color: CHART_COLORS.palette[5],
    category: "Effectifs",
  },
  effectif_sans_cpge_veto: {
    label: "Vétérinaire",
    format: "number" as const,
    color: CHART_COLORS.palette[6],
    category: "Effectifs",
  },
  effectif_sans_cpge_interd: {
    label: "Pluridisciplinaire",
    format: "number" as const,
    color: CHART_COLORS.palette[7],
    category: "Effectifs",
  },

  effectif_sans_cpge_du: {
    label: "Diplôme d'établissement",
    format: "number" as const,
    color: CHART_COLORS.palette[0],
    category: "Effectifs",
  },
  effectif_sans_cpge_dn: {
    label: "Diplôme national",
    format: "number" as const,
    color: CHART_COLORS.palette[1],
    category: "Effectifs",
  },

  effectif_sans_cpge_iut: {
    label: "Effectifs IUT",
    format: "number" as const,
    color: CHART_COLORS.palette[0],
    category: "Effectifs",
  },
  effectif_sans_cpge_ing: {
    label: "Effectifs ingénieur",
    format: "number" as const,
    color: CHART_COLORS.palette[1],
    category: "Effectifs",
  },

  part_droits_d_inscription: {
    label: "Part des droits d'inscription",
    format: "percent" as const,
    color: METRIC_COLORS.droitsInscription,
    category: "Parts",
    suffix: "%",
  },
  part_formation_continue_diplomes_propres_et_vae: {
    label: "part de la formation continue",
    format: "percent" as const,
    color: METRIC_COLORS.formationContinue,
    category: "Parts",
    suffix: "%",
  },
  part_taxe_d_apprentissage: {
    label: "part de la taxe d'apprentissage",
    format: "percent" as const,
    color: CHART_COLORS.palette[5],
    category: "Parts",
    suffix: "%",
  },
  part_valorisation: {
    label: "part de la valorisation",
    format: "percent" as const,
    color: CHART_COLORS.palette[6],
    category: "Parts",
    suffix: "%",
  },
  part_anr_hors_investissements_d_avenir: {
    label: "part de l'ANR hors investissements d'avenir",
    format: "percent" as const,
    color: "#A558A0",
    category: "Parts",
    suffix: "%",
  },
  part_anr_investissements_d_avenir: {
    label: "part de l'ANR investissements d'avenir",
    format: "percent" as const,
    color: CHART_COLORS.palette[7],
    category: "Parts",
    suffix: "%",
  },
  part_contrats_et_prestations_de_recherche_hors_anr: {
    label: "part des contrats de recherche",
    format: "percent" as const,
    color: METRIC_COLORS.contratsRecherche,
    category: "Parts",
    suffix: "%",
  },
  part_subventions_de_la_region: {
    label: "part des subventions régionales",
    format: "percent" as const,
    color: CHART_COLORS.palette[8],
    category: "Parts",
    suffix: "%",
  },
  part_subventions_union_europeenne: {
    label: "part des subventions UE",
    format: "percent" as const,
    color: METRIC_COLORS.subventionsUE,
    category: "Parts",
    suffix: "%",
  },
  part_autres_ressources_propres: {
    label: "part des autres ressources propres",
    format: "percent" as const,
    color: CHART_COLORS.palette[9],
    category: "Parts",
    suffix: "%",
  },
  part_autres_subventions: {
    label: "part des autres subventions",
    format: "percent" as const,
    color: CHART_COLORS.palette[10],
    category: "Parts",
    suffix: "%",
  },
  part_effectif_sans_cpge_iut: {
    label: "part des effectifs IUT",
    format: "percent" as const,
    color: CHART_COLORS.palette[0],
    category: "Parts",
    suffix: "%",
  },
  part_effectif_sans_cpge_ing: {
    label: "part des effectifs ingénieur",
    format: "percent" as const,
    color: CHART_COLORS.palette[1],
    category: "Parts",
    suffix: "%",
  },
  part_ress_formation: {
    label: "part des ressources formation",
    format: "percent" as const,
    color: CHART_COLORS.palette[11],
    category: "Parts",
    suffix: "%",
  },
  part_ress_recherche: {
    label: "part des ressources recherche",
    format: "percent" as const,
    color: CHART_COLORS.palette[11],
    category: "Parts",
    suffix: "%",
  },
  part_ress_autres_recette: {
    label: "part des autres ressources",
    format: "percent" as const,
    color: CHART_COLORS.palette[11],
    category: "Parts",
    suffix: "%",
  },
} as const;

export type MetricKey = keyof typeof METRICS_CONFIG;

export const METRIC_TO_PART: Partial<Record<MetricKey, MetricKey>> = {
  droits_d_inscription: "part_droits_d_inscription",
  formation_continue_diplomes_propres_et_vae:
    "part_formation_continue_diplomes_propres_et_vae",
  taxe_d_apprentissage: "part_taxe_d_apprentissage",
  valorisation: "part_valorisation",
  anr_hors_investissements_d_avenir: "part_anr_hors_investissements_d_avenir",
  anr_investissements_d_avenir: "part_anr_investissements_d_avenir",
  contrats_et_prestations_de_recherche_hors_anr:
    "part_contrats_et_prestations_de_recherche_hors_anr",
  subventions_de_la_region: "part_subventions_de_la_region",
  subventions_union_europeenne: "part_subventions_union_europeenne",
  autres_ressources_propres: "part_autres_ressources_propres",
  autres_subventions: "part_autres_subventions",
  effectif_sans_cpge_iut: "part_effectif_sans_cpge_iut",
  effectif_sans_cpge_ing: "part_effectif_sans_cpge_ing",
  tot_ress_formation: "part_ress_formation",
  tot_ress_recherche: "part_ress_recherche",
  tot_ress_autres_recette: "part_ress_autres_recette",
};

export const PREDEFINED_ANALYSES = {
  // Indicateurs financiers
  "ressources-total": {
    label: "Total des ressources",
    metrics: ["produits_de_fonctionnement_encaissables"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-vs-effectifs": {
    label: "Total des ressources vs effectifs d'étudiants (comparaison)",
    metrics: ["produits_de_fonctionnement_encaissables", "effectif_sans_cpge"],
    category: "Indicateurs financiers",
    showBase100: true,
  },
  "ressources-scsp": {
    label: "SCSP",
    metrics: ["scsp", "scsp_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "scsp-par-etudiant": {
    label: "SCSP par étudiant",
    metrics: ["scsp_par_etudiants", "scsp_par_etudiants_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "scsp-etudiant": {
    label: "SCSP étudiant",
    metrics: ["scsp_etudiants"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "scsp-comparaison-complete": {
    label: "SCSP, étudiants financés et SCSP par étudiant (base 100)",
    metrics: ["scsp", "scsp_etudiants", "scsp_par_etudiants"],
    category: "Indicateurs financiers",
    showBase100: true,
  },
  "ressources-propres": {
    label: "Total des ressources propres",
    metrics: ["ressources_propres", "ressources_propres_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-propres-encaissables": {
    label: "Ressources propres encaissables",
    metrics: [
      "ressources_propres_encaissables",
      "ressources_propres_encaissables_ipc",
    ],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "recettes-propres": {
    label: "Recettes propres",
    metrics: ["recettes_propres", "recettes_propres_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "autonomie-financiere": {
    label: "Autonomie financière",
    metrics: ["ressources_propres_produits_encaissables"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-formation": {
    label: "Ressources propres formation",
    metrics: ["tot_ress_formation", "tot_ress_formation_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-droits-inscription": {
    label: "Droits d'inscription",
    metrics: ["droits_d_inscription"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-formation-continue": {
    label: "Formation continue et VAE",
    metrics: ["formation_continue_diplomes_propres_et_vae"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-taxe-apprentissage": {
    label: "Taxe d'apprentissage",
    metrics: ["taxe_d_apprentissage"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-recherche": {
    label: "Ressources propres recherche",
    metrics: ["tot_ress_recherche", "tot_ress_recherche_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-valorisation": {
    label: "Valorisation",
    metrics: ["valorisation"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-anr-hors-ia": {
    label: "ANR hors investissements d'avenir",
    metrics: ["anr_hors_investissements_d_avenir"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-anr-ia": {
    label: "ANR investissements d'avenir",
    metrics: ["anr_investissements_d_avenir"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-contrats-recherche": {
    label: "Contrats et prestations de recherche",
    metrics: ["contrats_et_prestations_de_recherche_hors_anr"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-autres-recettes": {
    label: "Autres ressources propres (hors formation/recherche)",
    metrics: ["tot_ress_autres_recette", "tot_ress_autres_recette_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-subventions-region": {
    label: "Subventions régionales",
    metrics: ["subventions_de_la_region"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-subventions-ue": {
    label: "Subventions UE",
    metrics: ["subventions_union_europeenne"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-autres-propres": {
    label: "Autres ressources propres",
    metrics: ["autres_ressources_propres"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "ressources-autres-subventions": {
    label: "Autres subventions",
    metrics: ["autres_subventions"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "masse-salariale": {
    label: "Dépenses de masse salariale",
    metrics: ["charges_de_personnel", "charges_de_personnel_ipc"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "masse-salariale-poids": {
    label: "Poids sur produits encaissables",
    metrics: ["charges_de_personnel_produits_encaissables"],
    category: "Indicateurs financiers",
    showBase100: false,
  },
  "masse-salariale-comparaison": {
    label: "Charges et poids sur produits",
    metrics: [
      "charges_de_personnel_produits_encaissables",
      "charges_de_personnel",
    ],
    category: "Indicateurs financiers",
    showBase100: true,
  },

  // Santé financière
  "sante-resultat-net": {
    label: "Résultat net comptable",
    metrics: ["resultat_net_comptable", "resultat_net_comptable_ipc"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-resultat-net-hors-sie": {
    label: "Résultat net comptable hors SIE",
    metrics: [
      "resultat_net_comptable_hors_sie",
      "resultat_net_comptable_hors_sie_ipc",
    ],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-capacite-autofinancement": {
    label: "Capacité d'autofinancement",
    metrics: ["capacite_d_autofinancement", "capacite_d_autofinancement_ipc"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-caf-produits": {
    label: "CAF / Produits encaissables",
    metrics: ["caf_produits_encaissables"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-fonds-roulement": {
    label: "Fonds de roulement net global",
    metrics: [
      "fonds_de_roulement_net_global",
      "fonds_de_roulement_net_global_ipc",
    ],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-bfr": {
    label: "Besoin en fonds de roulement",
    metrics: [
      "besoin_en_fonds_de_roulement",
      "besoin_en_fonds_de_roulement_ipc",
    ],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-tresorerie": {
    label: "Trésorerie",
    metrics: ["tresorerie", "tresorerie_ipc"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-fonds-roulement-jours": {
    label: "Fonds de roulement en jours de fonctionnement",
    metrics: ["fonds_de_roulement_en_jours_de_fonctionnement"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-tresorerie-jours": {
    label: "Trésorerie en jours de fonctionnement",
    metrics: ["tresorerie_en_jours_de_fonctionnement"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-charges-produits": {
    label: "Charges décaissables / Produits encaissables",
    metrics: ["charges_decaissables_produits_encaissables"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-taux-remuneration": {
    label: "Taux de rémunération des permanents",
    metrics: ["taux_de_remuneration_des_permanents"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-ressources-propres": {
    label: "Ressources propres / Produits encaissables",
    metrics: ["ressources_propres_produits_encaissables"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-caf-immobilisations": {
    label: "CAF / Acquisitions d'immobilisations",
    metrics: ["caf_acquisitions_d_immobilisations"],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-solde-budgetaire": {
    label: "Solde budgétaire",
    metrics: ["solde_budgetaire", "solde_budgetaire_ipc"],
    category: "Santé financière",
    showBase100: false,
  },
  "charges-externes": {
    label: "Charges externes",
    metrics: ["charges_externes", "charges_externes_ipc"],
    category: "Santé financière",
    showBase100: false,
  },
  "excedent-brut-exploitation": {
    label: "Excédent brut d'exploitation (EBE)",
    metrics: [
      "excedent_brut_d_exploitation_ebe",
      "excedent_brut_d_exploitation_ebe_ipc",
    ],
    category: "Santé financière",
    showBase100: false,
  },
  "charges-fonctionnement": {
    label: "Charges de fonctionnement décaissables",
    metrics: [
      "charges_de_fonctionnement_decaissables",
      "charges_de_fonctionnement_decaissables_ipc",
    ],
    category: "Santé financière",
    showBase100: false,
  },
  "acquisitions-immobilisations": {
    label: "Acquisitions d'immobilisations",
    metrics: [
      "acquisitions_d_immobilisations",
      "acquisitions_d_immobilisations_ipc",
    ],
    category: "Santé financière",
    showBase100: false,
  },
  "sante-equilibre-exploitation": {
    label: "FR, BFR et Trésorerie",
    metrics: ["fonds_de_roulement_net_global", "besoin_en_fonds_de_roulement"],
    category: "Santé financière",
    showBase100: true,
  },

  // Étudiants et formation
  "formations-diplomes": {
    label: "Effectifs par type de diplôme",
    metrics: ["effectif_sans_cpge_dn", "effectif_sans_cpge_du"],
    category: "Étudiants et formation",
    showBase100: false,
    chartType: "stacked",
  },
  "formations-cycles": {
    label: "Effectifs par cursus (L/M/D)",
    metrics: [
      "effectif_sans_cpge_l",
      "effectif_sans_cpge_m",
      "effectif_sans_cpge_d",
    ],
    category: "Étudiants et formation",
    showBase100: false,
    chartType: "stacked",
  },
  "formations-degres": {
    label: "Effectifs par degré d'étude",
    metrics: [
      "effectif_sans_cpge_deg0",
      "effectif_sans_cpge_deg1",
      "effectif_sans_cpge_deg2",
      "effectif_sans_cpge_deg3",
      "effectif_sans_cpge_deg4",
      "effectif_sans_cpge_deg5",
      "effectif_sans_cpge_deg6",
      "effectif_sans_cpge_deg9",
    ],
    category: "Étudiants et formation",
    showBase100: false,
    chartType: "stacked",
  },
  "formations-disciplines": {
    label: "Effectifs par discipline",
    metrics: [
      "effectif_sans_cpge_dsa",
      "effectif_sans_cpge_llsh",
      "effectif_sans_cpge_theo",
      "effectif_sans_cpge_si",
      "effectif_sans_cpge_staps",
      "effectif_sans_cpge_sante",
      "effectif_sans_cpge_veto",
      "effectif_sans_cpge_interd",
    ],
    category: "Étudiants et formation",
    showBase100: false,
    chartType: "stacked",
  },
  "formations-iut": {
    label: "Effectifs en IUT",
    metrics: ["effectif_sans_cpge_iut"],
    category: "Étudiants et formation",
    showBase100: false,
  },
  "formations-ingenieur": {
    label: "Effectifs en formation d'ingénieur",
    metrics: ["effectif_sans_cpge_ing"],
    category: "Étudiants et formation",
    showBase100: false,
  },

  // Emplois
  "enseignants-emplois": {
    label: "Emplois enseignants (ETPT)",
    metrics: ["emploi_etpt"],
    category: "Emplois",
    showBase100: false,
  },
  "enseignants-taux": {
    label: "Taux d'encadrement",
    metrics: ["taux_encadrement"],
    category: "Emplois",
    showBase100: false,
  },
  "enseignants-comparaison": {
    label: "Taux et emplois ETPT",
    metrics: ["taux_encadrement", "emploi_etpt"],
    category: "Emplois",
    showBase100: true,
  },
} as const;

export type AnalysisKey = keyof typeof PREDEFINED_ANALYSES;
