// Mapping des codes ISO3 vers les continents
export const CONTINENT_BY_COUNTRY: Record<string, string> = {
  // Europe
  ALB: "Europe",
  AND: "Europe",
  AUT: "Europe",
  BLR: "Europe",
  BEL: "Europe",
  BIH: "Europe",
  BGR: "Europe",
  HRV: "Europe",
  CYP: "Europe",
  CZE: "Europe",
  DNK: "Europe",
  EST: "Europe",
  FIN: "Europe",
  FRA: "Europe",
  DEU: "Europe",
  GRC: "Europe",
  HUN: "Europe",
  ISL: "Europe",
  IRL: "Europe",
  ITA: "Europe",
  XKX: "Europe",
  LVA: "Europe",
  LIE: "Europe",
  LTU: "Europe",
  LUX: "Europe",
  MLT: "Europe",
  MDA: "Europe",
  MCO: "Europe",
  MNE: "Europe",
  NLD: "Europe",
  MKD: "Europe",
  NOR: "Europe",
  POL: "Europe",
  PRT: "Europe",
  ROU: "Europe",
  RUS: "Europe",
  SMR: "Europe",
  SRB: "Europe",
  SVK: "Europe",
  SVN: "Europe",
  ESP: "Europe",
  SWE: "Europe",
  CHE: "Europe",
  UKR: "Europe",
  GBR: "Europe",
  VAT: "Europe",
  FRO: "Europe",
  GIB: "Europe",
  GGY: "Europe",
  IMN: "Europe",
  JEY: "Europe",
  SJM: "Europe",

  // Afrique
  DZA: "Afrique",
  AGO: "Afrique",
  BEN: "Afrique",
  BWA: "Afrique",
  BFA: "Afrique",
  BDI: "Afrique",
  CPV: "Afrique",
  CMR: "Afrique",
  CAF: "Afrique",
  TCD: "Afrique",
  COM: "Afrique",
  COD: "Afrique",
  COG: "Afrique",
  CIV: "Afrique",
  DJI: "Afrique",
  EGY: "Afrique",
  GNQ: "Afrique",
  ERI: "Afrique",
  SWZ: "Afrique",
  ETH: "Afrique",
  GAB: "Afrique",
  GMB: "Afrique",
  GHA: "Afrique",
  GIN: "Afrique",
  GNB: "Afrique",
  KEN: "Afrique",
  LSO: "Afrique",
  LBR: "Afrique",
  LBY: "Afrique",
  MDG: "Afrique",
  MWI: "Afrique",
  MLI: "Afrique",
  MRT: "Afrique",
  MUS: "Afrique",
  MAR: "Afrique",
  MOZ: "Afrique",
  NAM: "Afrique",
  NER: "Afrique",
  NGA: "Afrique",
  RWA: "Afrique",
  STP: "Afrique",
  SEN: "Afrique",
  SYC: "Afrique",
  SLE: "Afrique",
  SOM: "Afrique",
  ZAF: "Afrique",
  SSD: "Afrique",
  SDN: "Afrique",
  TZA: "Afrique",
  TGO: "Afrique",
  TUN: "Afrique",
  UGA: "Afrique",
  ZMB: "Afrique",
  ZWE: "Afrique",
  REU: "Afrique",
  MYT: "Afrique",
  SHN: "Afrique",

  // Amérique du Nord
  CAN: "Amérique du Nord",
  USA: "Amérique du Nord",
  MEX: "Amérique du Nord",
  GTM: "Amérique du Nord",
  BLZ: "Amérique du Nord",
  HND: "Amérique du Nord",
  SLV: "Amérique du Nord",
  NIC: "Amérique du Nord",
  CRI: "Amérique du Nord",
  PAN: "Amérique du Nord",
  CUB: "Amérique du Nord",
  HTI: "Amérique du Nord",
  DOM: "Amérique du Nord",
  JAM: "Amérique du Nord",
  TTO: "Amérique du Nord",
  BHS: "Amérique du Nord",
  BRB: "Amérique du Nord",
  GRD: "Amérique du Nord",
  ATG: "Amérique du Nord",
  DMA: "Amérique du Nord",
  LCA: "Amérique du Nord",
  VCT: "Amérique du Nord",
  KNA: "Amérique du Nord",
  GLP: "Amérique du Nord",
  MTQ: "Amérique du Nord",
  PRI: "Amérique du Nord",
  VIR: "Amérique du Nord",
  ABW: "Amérique du Nord",
  CUW: "Amérique du Nord",
  SXM: "Amérique du Nord",
  BMU: "Amérique du Nord",
  CYM: "Amérique du Nord",
  GRL: "Amérique du Nord",
  SPM: "Amérique du Nord",

  // Amérique du Sud
  ARG: "Amérique du Sud",
  BOL: "Amérique du Sud",
  BRA: "Amérique du Sud",
  CHL: "Amérique du Sud",
  COL: "Amérique du Sud",
  ECU: "Amérique du Sud",
  GUY: "Amérique du Sud",
  PRY: "Amérique du Sud",
  PER: "Amérique du Sud",
  SUR: "Amérique du Sud",
  URY: "Amérique du Sud",
  VEN: "Amérique du Sud",
  GUF: "Amérique du Sud",
  FLK: "Amérique du Sud",

  // Asie
  AFG: "Asie",
  ARM: "Asie",
  AZE: "Asie",
  BHR: "Asie",
  BGD: "Asie",
  BTN: "Asie",
  BRN: "Asie",
  KHM: "Asie",
  CHN: "Asie",
  GEO: "Asie",
  HKG: "Asie",
  IND: "Asie",
  IDN: "Asie",
  IRN: "Asie",
  IRQ: "Asie",
  ISR: "Asie",
  JPN: "Asie",
  JOR: "Asie",
  KAZ: "Asie",
  KWT: "Asie",
  KGZ: "Asie",
  LAO: "Asie",
  LBN: "Asie",
  MAC: "Asie",
  MYS: "Asie",
  MDV: "Asie",
  MNG: "Asie",
  MMR: "Asie",
  NPL: "Asie",
  PRK: "Asie",
  OMN: "Asie",
  PAK: "Asie",
  PSE: "Asie",
  PHL: "Asie",
  QAT: "Asie",
  SAU: "Asie",
  SGP: "Asie",
  KOR: "Asie",
  LKA: "Asie",
  SYR: "Asie",
  TWN: "Asie",
  TJK: "Asie",
  THA: "Asie",
  TLS: "Asie",
  TUR: "Asie",
  TKM: "Asie",
  ARE: "Asie",
  UZB: "Asie",
  VNM: "Asie",
  YEM: "Asie",

  // Océanie
  AUS: "Océanie",
  FJI: "Océanie",
  KIR: "Océanie",
  MHL: "Océanie",
  FSM: "Océanie",
  NRU: "Océanie",
  NZL: "Océanie",
  PLW: "Océanie",
  PNG: "Océanie",
  WSM: "Océanie",
  SLB: "Océanie",
  TON: "Océanie",
  TUV: "Océanie",
  VUT: "Océanie",
  NCL: "Océanie",
  PYF: "Océanie",
  GUM: "Océanie",
  ASM: "Océanie",
  COK: "Océanie",
  NIU: "Océanie",
  TKL: "Océanie",
  WLF: "Océanie",
};

export const CONTINENT_COLORS: Record<string, string> = {
  Europe: "#7C3AED",
  Afrique: "#f59e0b",
  "Amérique du Nord": "#10b981",
  "Amérique du Sud": "#14b8a6",
  Asie: "#ef4444",
  Océanie: "#8b5cf6",
  Autre: "#94a3b8",
};

export const CONTINENT_NAMES: Record<string, Record<string, string>> = {
  Europe: { fr: "Europe", en: "Europe" },
  Afrique: { fr: "Afrique", en: "Africa" },
  "Amérique du Nord": { fr: "Amérique du Nord", en: "North America" },
  "Amérique du Sud": { fr: "Amérique du Sud", en: "South America" },
  Asie: { fr: "Asie", en: "Asia" },
  Océanie: { fr: "Océanie", en: "Oceania" },
  Autre: { fr: "Autre", en: "Other" },
};

export function getContinentFromCountryCode(countryCode: string): string {
  return CONTINENT_BY_COUNTRY[countryCode] || "Autre";
}
