name: Staging deployment

on:
  push:
    branches:
      - staging

env:
  # Must match k8s deployment name
  DEPLOYMENT: datasupr
  DEPLOYMENT_NAMESPACE: datasupr
  DEPLOYMENT_URL: https://datasupr.staging.dataesr.ovh
  MM_NOTIFICATION_CHANNEL: 'bots'

jobs:
  publish-ghcr:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v3

      - name: Get Tag
        id: version
        run: echo "tag=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Log into registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --silent && npm run build --mode=staging

      - name: 🐋 Build Docker image
        run: docker build -t ${{ github.repository }} .

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag ${{ github.repository }} $IMAGE_ID:${{ steps.version.outputs.tag }}
          docker push $IMAGE_ID:${{ steps.version.outputs.tag }}

  deploy:
    name: Update staging deployment
    runs-on: ubuntu-latest
    needs: publish-ghcr
    steps:
      - name: Deploy to Cluster
        id: kubectl-deploy
        uses: dataesr/kubectl-deploy@v1.1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DOAD_STAGING }}
        with:
          namespace: ${{ env.DEPLOYMENT_NAMESPACE }}
          restart: ${{ env.DEPLOYMENT }}

  notify:
    needs: deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: dataesr/mm-notifier-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          mattermost_channel: ${{ env.MM_NOTIFICATION_CHANNEL}}
          deployment_url: ${{ env.DEPLOYMENT_URL }}